#! /bin/sh

echo -n "270" > /sys/class/gpio/export
sleep 1
echo -n "out" > /sys/class/gpio/gpio270/direction

echo -n "272" > /sys/class/gpio/export
sleep 1
echo -n "out" > /sys/class/gpio/gpio272/direction
